
create table db3.CONTRACT
(
	ID NUMBER not null
		primary key,
	CNT_NAME VARCHAR2(100),
	CNT_BUYER_NAME VARCHAR2(100),
	CNT_SELLER_NAME VARCHAR2(100)
);



INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (1, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (2, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (3, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (4, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (5, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (6, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (7, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (8, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (9, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (10, '合同名称', '买方名称', '卖方名称');

commit;